[package]
name    = "ferrite-notify"
version.workspace = true
edition.workspace = true

[[bin]]
name = "ferrite-notify"
path = "src/main.rs"

[dependencies]
serde      = { workspace = true }
serde_json = { workspace = true }
toml       = { workspace = true }
lettre     = { version = "0.11", default-features = false, features = ["smtp-transport", "native-tls", "builder"] }
